# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: test JQ
        run: |
          status=$(echo 'fsgsdgsd' | jq '.fields.status.name' 2>/dev/null)
          echo $status
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          if [ -z '' ]; then
            echo "::error::Jira Issue Status is empty!"
            exit 1
          fi
